### ISSUE TITLE
What is the serious issue TES3Merge is trying to tell me about?

### ISSUE THREAD

**Issue by clydemcelroyseo** [NullCascade/TES3Merge#20]
Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at TES3Lib.Base.Subrecord.Equals(Object obj) in D:\Projects\Morrowind\TES3Merge\TES3Tool\TES3Lib\Base\Subrecord.cs:line 122
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.ValueTuple`2.Equals(ValueTuple`2 other)
   at System.ValueTuple`2.Equals(Object obj)
   at TES3Merge.TES3LibExtensions.PublicPropertyComparer.Equals(Object a, Object b) in D:\Projects\Morrowind\TES3Merge\TES3Merge\Extensions\TES3LibExtensions.cs:line 24
   at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at TES3Merge.TES3LibExtensions.MergeProperty(PropertyInfo property, Object obj, Object first, Object next) in D:\Projects\Morrowind\TES3Merge\TES3Merge\Extensions\TES3LibExtensions.cs:line 50
   at TES3Merge.TES3LibExtensions.MergeWith(Record record, Record next, Record first) in D:\Projects\Morrowind\TES3Merge\TES3Merge\Extensions\TES3LibExtensions.cs:line 143
   at TES3Merge.Program.Main(String[] args) in D:\Projects\Morrowind\TES3Merge\TES3Merge\Program.cs:line 411

Do you need all of the data from the log or can you give me a hint without it?

**Comment by NullCascade** [comment]
What version of TES3Merge are you using? Try updating, it should give you better information.
