### ISSUE TITLE
Archive 'PT_Data.bsa' could not be found.

### ISSUE THREAD

**Issue by Pushkatu** [NullCascade/TES3Merge#42]
TES3Merge v0.10.1.0.
Using encoding: Western European (Windows)
Installation folder: D:\Morrowind - YAJAN\Stock Game Folder
Supported record types: ACTI, ALCH, APPA, ARMO, BODY, BOOK, BSGN, CELL, CLAS, CLOT, CONT, CREA, DOOR, ENCH, GMST, INGR, LEVC, LEVI, LIGH, LOCK, MGEF, MISC, NPC_, PROB, RACE, REPA, SKIL, SNDG, SOUN, SPEL, STAT, WEAP
An unhandled exception has occurred. Traceback:
Archive 'PT_Data.bsa' could not be found.
   at TES3Merge.Util.MorrowindInstallation.MapArchiveFiles()
   at TES3Merge.Util.MorrowindInstallation.LoadDataFiles()
   at TES3Merge.Util.Installation.GetDataFile(String path)
   at TES3Merge.Commands.MergeAction.Merge(Settings settings)
   at TES3Merge.Commands.MergeAction.Run(Settings settings)

**Comment by Pushkatu** [comment]
I'm using Mod Organizer 2.4.4 if that helps in any way.

**Comment by justastranger** [comment]
Running into the same error with the same MO2 version. The error would be 100x more helpful if it named and shamed the offending mod.
