### ISSUE TITLE
TES3Merge v0.10.1.0. "A serious error has occurred"

### ISSUE THREAD

**Issue by mercurybard** [NullCascade/TES3Merge#43]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/10460271/TES3Merge.log)

Whole log attached (I think), but here's where it goes wonky:
An unhandled exception has occurred. Traceback:
One or more errors occurred. (Exception has been thrown by the target of an invocation.) (Exception has been thrown by the target of an invocation.) (Exception has been thrown by the target of an invocation.) (Exception has been thrown by the target of an invocation.) (Exception has been thrown by the target of an invocation.)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at TES3Lib.TES3.TES3Load(String filePath, List`1 filteredGrops)
   at TES3Merge.Commands.MergeAction.Merge(Settings settings)
   at TES3Merge.Commands.MergeAction.Run(Settings settings)

**Comment by Teraunce** [comment]
Bumping this with my own log and the esp throwing the error.
[TES3Merge1.log](https://github.com/NullCascade/TES3Merge/files/11073445/TES3Merge1.log)
[House of Clues 2 Return of the Clues V1.1.zip](https://github.com/NullCascade/TES3Merge/files/11073449/House.of.Clues.2.Return.of.the.Clues.V1.1.zip)
