### ISSUE TITLE
TES3Merge v0.11.0.0. ... An unhandled exception has occurred

### ISSUE THREAD

**Issue by Tezrel** [NullCascade/TES3Merge#44]
Hey thanks for TES3Merge!

I just installed .NET 6.0 Desktop Runtime (v6.0.24), copied the new TES3Merge v0.11 files into my Morrowind directory, and I get this error below. Is the Archive "'_BetterBodies.bsa' could not be found._" note because I have a mod dependant on it somewhere in my load order?

Thank you,

- - - -

TES3Merge v0.11.0.0.
Using encoding: Western European (Windows)
Installation folder: C:\Games\steamapps\common\Morrowind
Supported record types: ACTI, ALCH, APPA, ARMO, BODY, BOOK, BSGN, CELL, CLAS, CLOT, CONT, CREA, DOOR, ENCH, GMST, INGR, LEVC, LEVI, LIGH, LOCK, MGEF, MISC, NPC_, PROB, RACE, REPA, SKIL, SNDG, SOUN, SPEL, STAT, WEAP
An unhandled exception has occurred. Traceback:
Archive 'BetterBodies.bsa' could not be found.
   at TES3Merge.Util.MorrowindInstallation.MapArchiveFiles()
   at TES3Merge.Util.MorrowindInstallation.LoadDataFiles()
   at TES3Merge.Util.Installation.GetDataFile(String path)
   at TES3Merge.Commands.MergeAction.Merge(Settings settings)
   at TES3Merge.Commands.MergeAction.Run(Settings settings)

![image](https://github.com/NullCascade/TES3Merge/assets/149846408/b5767f1c-a99d-45f9-b2ca-f9747e4c08e5)

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/13255489/TES3Merge.log)

**Comment by Tezrel** [comment]
Pardon my noobery ignorance. I hope this is the correctly uploaded file.

Now getting a different error message:

TES3Merge v0.11.0.0.
Installation folder: C:\Games\steamapps\common\Morrowind
Supported record types: ACTI, ALCH, APPA, ARMO, BODY, BOOK, BSGN, CELL, CLAS, CLOT, CONT, CREA, DOOR, ENCH, GMST, INGR, LEVC, LEVI, LIGH, LOCK, MGEF, MISC, NPC_, PROB, RACE, REPA, SKIL, SNDG, SOUN, SPEL, STAT, WEAP
[Merge] took 12921 ms.
**A serious error has occurred.** Please post the TES3Merge.log file to GitHub: https://github.com/NullCascade/TES3Merge/issues
Press any key to exit...



[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/13255519/TES3Merge.log)

**Comment by FeuerTiger86** [comment]
I'm having a similar issue, but for me it starts the merge and fails after a few records. I'm currently building up a new modded installation and I regularly re-generate the Merged Objects.esp to check conflicts with tes3view (xEdit). Most of the time it works, but sometimes after I changed something in the load order, I get this error: An unhandled exception has occurred
It always fails at a SKIL record, and I found that when I move [Slower Leveling Speed](https://www.nexusmods.com/morrowind/mods/50262) to a different spot in my load order (it can still have the exact same position relative to conflicting mods, and I always load this after the - very few - mods that also change Skills), the Merged Objects.esp will generate just fine.

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/13325615/TES3Merge.log)
